# Generated by Django 4.2.1 on 2023-06-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modalidad',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('modal', models.CharField(max_length=100, verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='oferta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='items')),
                ('ingredientes', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.modalidad')),
            ],
            options={
                'verbose_name': 'Plsatos y Bevidas',
                'verbose_name_plural': 'Platos y Bevidas',
            },
        ),
    ]
