# Generated by Django 3.2.16 on 2023-04-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'verbose_name': 'Plsatos y Bevidas', 'verbose_name_plural': 'Platos y Bevidas'},
        ),
    ]
